### ISSUE TITLE
SetState in onDateSelected

### ISSUE THREAD

**Issue by OpticNectar** [ikicodedev/calendar_timeline#8] opened 2020-06-22 15:59 UTC
Calling `SetState` in the `onDateSelected` call back causes the calendar to not work. When you click a day it just does nothing.

**Comment by ikicodedev** [comment] 2020-06-26 10:42
I cannot reproduce the error. What version of the package are you using? Can you share the code example that gives you this error?

**Comment by OpticNectar** [comment] 2020-06-26 14:17
I mentioned this in another bug, but if you use the code below and click any day, nothing happens.

```
CalendarTimeline(
  initialDate: DateTime.now(),
  firstDate: DateTime.now(),
  lastDate: DateTime.now().add(Duration(days: 7)),
  onDateSelected: (date) {
    setState(() {
      startDate = date;
    });
  },
)

```

**Comment by ikicodedev** [comment] 2020-07-05 08:49
Duplicate of #9

**Closed by ikicodedev** 2020-07-05 08:49 UTC
Labels: bug
